### ISSUE TITLE
Tool for Batch Adding Noise to point cloud

### ISSUE THREAD

**Issue by Hao-HUST** [paulguerrero/pcpnet#1]
Hi, great work and thanks for sharing code.

But, is there some auto tools for adding noise to point cloud on your project(Not add noise one by one, just add noise for a batch of point clouds)?

**Comment by paulguerrero** [comment]
Hi, the dataset generation was done with separate tools that are not in the repository. We did not want to mix them in here because a) they are messy and not well documented and b) they are written in Matlab.

However, adding noise should be relatively straight-forward, with torch for example:
```python
points += torch.normal(torch.zeros(points.shape), noise_strength)
```

If you want to add noise during training, I would recommend editing `PointcloudPatchDataset.__getitem__` in `dataset.py`
